extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_TESTMAT_RED_lights;
extern Lights1 bob_dl_TESTMAT_BLUE_lights;
extern Lights1 bob_dl_movingSand_lights;
extern u8 bob_dl_sand_rgba16[];
extern Vtx bob_dl_MAIN_FLOOR_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_MAIN_FLOOR_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_SANDYFLOOR_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_SANDYFLOOR_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_TESTMAT_RED[];
extern Gfx mat_bob_dl_TESTMAT_BLUE[];
extern Gfx mat_bob_dl_movingSand[];
extern Gfx bob_dl_MAIN_FLOOR_mesh_layer_1[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_SANDYFLOOR_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
